PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?obligationInstance ?articleCitation ?legalText ?responsibleActor
WHERE {

  ?obligationClass rdfs:subClassOf* :Obligation .
  ?obligationInstance rdf:type ?obligationClass .
  
  ?obligationInstance skos:prefLabel ?articleCitation .
  ?obligationInstance skos:definition ?legalText .
  
  # Retrieve the responsible actor
  ?obligationInstance :isAssignedTo ?responsibleActor .
}
ORDER BY ?articleCitation